apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.l2AdvertisementName }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - {{ .Values.ipAddressPoolName | quote }}
